### ISSUE TITLE
[ISSUE] ERROR when set "unavailable" timezone

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lncalendar#1]
#### First of all i wanna say thank you for this extension. It´s a really helpfull one. Thanks!

Now I would like to report about the errors I encountered when trying the extension.

### **Issue**
When try to set a "unavailable" timezone in my calender i get the follwing output:

##### Screenshot:
![setUnavailable](https://github.com/lnbits/lncalendar/assets/106493492/b8a6eaf3-a6bc-42f4-b40b-e1e5ac4ecda3)

##### Log Output:
`2024-01-11 18:47:20.68 | INFO | 178.200.54.5:0 - "GET /lncalendar/api/v1/unavailable/WAqGuGU6edaWM68KfbDRaV HTTP/1.1" 200
2024-01-11 18:47:26.41 | ERROR | HTTPException 403: Not your schedule.
2024-01-11 18:47:26.41 | INFO | 178.200.54.5:0 - "POST /lncalendar/api/v1/unavailable HTTP/1.1" 403`

### Replicate:
1. Create LNCalender
2. Go to tap "Set unavailable"
3. Try set a "Unvailable" timezone
4. See error output 

Version:
LNBits 0.11.3
LNCalender 0.1.0

**Comment by talvasconcelos** [comment]
Oh WOW!! Thank you for beta testing the extension! 

I'll review your reported issues and release a new  version soon!

**Comment by talvasconcelos** [comment]
Fixed in #v0.1.1
