### ISSUE TITLE
[ISSUE] Not payed invoices set booked time slot set as "true" appointment in calender

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lncalendar#2]
### **[ISSUE]**
As a customer, when i going to book a time slot and do not pay the invoice for any reason the initiator of the calender get a fixed appointment in his calender.

##### Screenshot

**Info:** The two blue marked appointments are not payed invoices.

![notPayed_4](https://github.com/lnbits/lncalendar/assets/106493492/08ac9910-a2bf-463a-b249-d3c64a6c15f7)

### Replicate
1. Run LNCalender on your instance
2. Create an calender
3. Simulate a customer and book an appointment. 
4. Do not pay the invoice
5. As the initiator. go and look in section "Appointments"
6. See a Appointment which is not payed

### Version
LNBits 0.11.3
LNcalender 0.1.0

**Comment by talvasconcelos** [comment]
On next release, you'll see which ones are unpaid, and they get purged after 24h!

**Comment by DoktorShift** [comment]
nice release on https://github.com/lnbits/lncalendar/compare/v0.1.0...v0.1.1 
I able now to see that there is a booking which is not payed yet. The purge after 24 hours also working. Time slot is available again after purge.
