### ISSUE TITLE
[ISSUE] "Payment does not exist" output after successful payment as a customer

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lncalendar#3]
### ISSUE
As a customer i payed my appointment with success. I tracked in between on the incoming wallet. 

While as a customer i get an Output notification **"Payment does not exist"** which could lead to a confused customer. Did it work? Is it failed?

#### Screenshot
![afterPayedInvoice](https://github.com/lnbits/lncalendar/assets/106493492/c748142c-1de4-4794-b39f-ad37bf442fb3)

_note: The count is ongoing everytime the page is refreshing_

### Replicate
1. As a customer. Make an appointment and pay the invoice
2. See the output after payed invoice.

_note: Sadly i was not able to replicate this issue. Had it once._

### Version
LNBits 0.11.3
LNcalender 0.1.0

**Comment by talvasconcelos** [comment]
Fixed in #v0.1.1
