### ISSUE TITLE
[ISSUE] Text formating broken on mobile devices

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lncalendar#4]
### **ISSUE**
As a customer i wanna book an apointment and add a optional message. This message will be broken in terms of formating rules. This only appears on mobile devices while its working as intendend on stand alone pc´s.

#### _Example sentence:_
"I going to demonstrate with this text that there is some issue on mobile devices while its working on a stand alone personal computer without problems"

#### Screenshot
![issue 4 LNcalender](https://github.com/lnbits/lncalendar/assets/106493492/c0ada5cc-bad3-4503-a499-3c42d10ace1a)

### Replicate
1. As a customer on mobile device go to the calender and select a date.
2. Add an additional message
3. See your sentences get mixed up

### Version
LNBits 0.11.3
LNcalender 0.1.0
OS: Android 7, Android 12, Android 13 --> Chrome and Opera

**Note**
On IOS device with IOS 17.2.1 with safari its working

#### Screenshot
![issue 4 IOS](https://github.com/lnbits/lncalendar/assets/106493492/4342b0c9-1949-498d-ad2d-e10254dc192d)

**Comment by talvasconcelos** [comment]
Can't reproduce this. Seems browser issues maybe!

**Comment by arcbtc** [comment]
Its because you have trim on prob 
https://github.com/lnbits/lncalendar/blob/abb564841dc2651e20dcbdaa10145b293de035e6/templates/lncalendar/display.html#L27
Change to regular `v-model`
